[Feature] Database 클래스 추가
dezyon1/Be1stReviewer pull request #22
Opened 2022-03-03 23:46 UTC by karosung

Employee 정보를 담을 자료구조와 자료구조의 접근을 위한 클래스 정의

2022-03-03 23:50 UTC, dezyon1 requested changes

2022-03-03 23:50 UTC, dezyon1 commented on EmployeeManagementSystem/EmployeeManagementSystem/Database.h
> +class Database : public IDatabase<record> {
vector형태의 database이니 클래스명은 VectorDatabase로 변경하는게 좋을것 같습니다.

2022-03-03 23:50 UTC, dezyon1 commented on EmployeeManagementSystem/EmployeeManagementSystem/Database.h
> +	virtual string del(string const& column, string const& keyword) override { return ""; };
return형태는 여러개의 record형태가 될테니 vector<record>가 좋을것 같습니다.

2022-03-03 23:57 UTC, karosung commented on EmployeeManagementSystem/EmployeeManagementSystem/Database.h
> +class Database : public IDatabase<record> {
넵 수정해서 올리겠습니다

2022-03-03 23:57 UTC, Soeun222 commented
LGTM, 수고하셨습니다~!

2022-03-03 23:58 UTC, Soeun222 approved these changes
LGTM, 수고하셨습니다~!

2022-03-04 00:01 UTC, dezyon1 requested changes

2022-03-04 00:01 UTC, dezyon1 commented on EmployeeManagementSystem/EmployeeManagementSystem/Database.h
> +	virtual vector<record>& mod(string const& column, string const& keyword,
vector<record>& 형태로 리턴하게되면 함수 종료후 vector<record> temp 변수가 사라지게 될거같습니다.
우선 다소 비효율적이겠지만 vector<record> 형태로 리턴하는게 좋을듯합니다.

2022-03-04 00:02 UTC, karosung commented on EmployeeManagementSystem/EmployeeManagementSystem/Database.h
> +	virtual vector<record>& mod(string const& column, string const& keyword,
& 삭제하여 반영하였습니다~!

2022-03-04 00:05 UTC, dezyon1 approved these changes
좋은 코드가 작성된것같습니다.
고생하셨습니다.

2022-03-04 00:06 UTC, merged

2022-03-04 00:07 UTC, ShinDongHyuk commented on EmployeeManagementSystem/EmployeeManagementSystem/Database.h
> +	virtual vector<record> del(string const& column, string const& keyword) = 0;
실제로 데이터 관리하는데 사용되는 자료구조는 숨기기 위한 코드이군요.
리턴타입 vector는 자료구조 클래스 상관없이 결과물 전달하기 위해 사용하는 자료구조같네요.