[Refactoring] static string 변수 선언 및 사용
dezyon1/Be1stReviewer pull request #45
Opened 2022-03-07 07:24 UTC by Soeun222

2022-03-07 07:54 UTC, karosung reviewed
수정하시느라 너무 고생하셨는데, 혹시 상수라는걸 알 수 있는 네이밍일 필요는 없겠죠?
일반 변수랑

2022-03-07 07:54 UTC, karosung commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
너무 고생하셨는데, 의견 드리자면
Column Cmd Option으로 구분해서 선언하는건 어떨까요? 상수 변수 이름이 일반 변수랑 비슷해서 헷갈릴 수도 있을 것 같아서요.
예를 들어
Col::PhoneNum
Opt::P
Cmd::Add 이런식은 어떨지 의견 드립니다.~

2022-03-07 07:57 UTC, dezyon1 requested changes

2022-03-07 07:57 UTC, dezyon1 commented on EmployeeManagementSystem/EmployeeManagementSystem/Employee.cpp
>  #include <regex>
명시적으로 Common.h 파일 include 추가하면 좋을것 같습니다.

2022-03-07 07:57 UTC, dezyon1 commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
상수값의 변조 방지를 위해 const 를 추가해야하지 않을까요?

2022-03-07 08:06 UTC, ShinDongHyuk commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
동의합니다. 상수값은 static const로 많이들 정의하는 것 같습니다.

2022-03-07 08:10 UTC, ShinDongHyuk commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
상수 변수는 대문자를 보통 사용했던 것 같습니다.

2022-03-07 08:10 UTC, Soeun222 commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
동의합니다. 수정해서 반영하도록 하겠습니다~!! 피드백 감사합니다

2022-03-07 08:11 UTC, Soeun222 commented on EmployeeManagementSystem/EmployeeManagementSystem/Employee.cpp
>  #include <regex>
Common.h 파일이 Employee.h에 포함되어있는데 Employee.cpp에도 include할 필요가 있을까요?

2022-03-07 08:15 UTC, Soeun222 commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
그렇네요~! 호성님과 동혁님 말씀대로 상수 변수와 일반 변수가 헷갈릴 소지가 있군요! 그럼 대문자로 변경해보도록 하겠습니다~!

2022-03-07 23:41 UTC, dezyon1 commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
https://google.github.io/styleguide/cppguide.html#Constant_Names
위 링크의 가이드를 보면 특별히 대문자를 쓰진 않는거같아서 저는 변경안해도 될것같습니다.

2022-03-07 23:43 UTC, dezyon1 commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
namespace 지정했으므로 static은 필요없을것같습니다. const만 추가해주시면 될듯합니다.

2022-03-07 23:46 UTC, Soeun222 commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
앞에 k를 붙여서 구분하는 방법도 있군요~! 대문자로 이미 바꿔버려서 이 방법은 다음에 참고해보도록 하겠습니다! 감사합니다!

2022-03-07 23:49 UTC, Soeun222 commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
앗 그러네요~!! 수정하도록 하겠습니다! 감사합니다.

2022-03-07 23:51 UTC, dezyon1 approved these changes

2022-03-07 23:52 UTC, dezyon1 approved these changes
수정사항 확인하였습니다. 고생하셨습니다.

2022-03-07 23:53 UTC, Soeun222 commented on EmployeeManagementSystem/EmployeeManagementSystem/Common.h
> +	static string employeeNumStr = "employeeNum";
수정완료하였습니다!

2022-03-07 23:58 UTC, karosung approved these changes
LGTM 고생 많으셨습니다.

2022-03-08 00:02 UTC, ShinDongHyuk approved these changes
LGTM, 수고하셨습니다.

2022-03-08 00:06 UTC, merged